# Generated by Django 4.2.7 on 2024-02-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biens',
            new_name='Article',
        ),
    ]
