# Generated by Django 4.2.7 on 2024-02-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_profilutilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilUtilisateur',
        ),
    ]
