# Generated by Django 4.2.7 on 2024-02-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0007_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
