# Generated by Django 4.2.7 on 2024-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='availability_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='availability_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
