# Generated by Django 4.2.7 on 2024-02-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0009_article_availability_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='availability_end_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='availability_start_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='disponible',
        ),
    ]
