# Generated by Django 4.2.7 on 2024-02-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0011_article_disponible_article_est_reserve_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
