# Generated by Django 4.2.7 on 2024-02-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0012_delete_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='est_reserve',
            new_name='reserved',
        ),
    ]
