# Generated by Django 4.2.7 on 2024-02-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0013_rename_est_reserve_article_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reserved',
        ),
    ]
