# Generated by Django 4.2.7 on 2024-02-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0016_reservation_date_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='notation_moyenne',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='biens.article')),
            ],
        ),
    ]
