# Generated by Django 4.2.7 on 2024-02-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0017_article_avis_article_notation_moyenne_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avis',
        ),
        migrations.RemoveField(
            model_name='article',
            name='notation_moyenne',
        ),
    ]
