# Generated by Django 4.2.7 on 2024-03-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biens', '0020_remove_note_note_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='note',
            name='nombre_etoiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.article'),
        ),
        migrations.AlterField(
            model_name='note',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
