# Generated by Django 4.2.7 on 2024-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0029_remove_article_image_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
