# Generated by Django 4.2.7 on 2024-03-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
